### ISSUE TITLE
Fallback Image

### ISSUE THREAD

**Issue by harrybigspring** [bigspring/M3#12]
The fallback image needs to have the custom image sizes we have set applied to it.

Currently the image is placed in assets/img and it's a fixed size whenever it is used as a fallback which can cause issues when using <?php the_monolith_post_thumbnail( '$size' ); ?>.

Implement a "Settings" option similar to the current monolith "Company Details"
or
An ACF into the "Options" page.

We would upload the fallback at sprint 0 or kitchen sink.

**Comment by jrgmartin** [comment]
Moved to internal issue tracking tool
