### ISSUE TITLE
Woocommerce support

### ISSUE THREAD

**Issue by jrgmartin** [bigspring/M3#28]
Needs discussion and consideration as to what's required

**Comment by simonpmiles** [comment]
Dave says we could do a check for Woo and then run the necessary filters. See Dave for more info.

We should also include woocommerce sass and the woocommerce folder with a bunch of overrides that are M3 friendly.

**Comment by dmseaton** [comment]
This will necessitate the following:

- Separate Woocommerce folder for WC-related functions/hooks
- WC integration into theme
- Styles
-- Unhook WC styles
-- Add custom WC SASS styles (add templates as required to test but remove before committing)

Ideally the WC folder will be included only [if WC is detected](http://wordpress.stackexchange.com/questions/159177/how-to-check-if-woocommerce-is-activated-in-theme) but a commented-out include in ./functions.php should be fine.
