### ISSUE TITLE
Child theme support

### ISSUE THREAD

**Issue by dmseaton** [bigspring/M3#30]
FoundationPress isn't configured to serve as a parent theme by default so changes will be necessary.

See the Child Theming guide what I wrote. The [child theme changes from M2](https://gist.github.com/dmseaton/c17489db278b1f1e6c8d) will be useful in part but the Builder will need to be modified to reflect the new directory structure. The Gulp config will need to be also need to be reviewed, and a general test of the FP base plus our modifications would be prudent.

**Comment by juliotaylor** [comment]
This is now being handled in https://github.com/bigspring/m3-junior
