### ISSUE TITLE
Kitchen sink page template

### ISSUE THREAD

**Issue by harrybigspring** [bigspring/M3#33]
A lot of the items in this page do not seem to work, accordions for example.

**Comment by jam-bigspring** [comment]
Kitchen sink elements seem to be working OK now.

Accordions open fine but don't close even though they look like they should.

**Comment by harrybigspring** [comment]
The accordions work like this by default so they are ok. The slider elements cause a console error. I don't know how important this is as we have never used them in any projects I'm aware of.
