### ISSUE TITLE
Issue when aligning an image in content

### ISSUE THREAD

**Issue by jam-bigspring** [bigspring/M3#48]
When an image is aligned left or right it shows a white bar on the side of the image to represent the padding on the image. The padding seems correct for text but does not take bullet points into account.

**Comment by simonpmiles** [comment]
This is a very particular issue and perhaps a quirk with html rather than our coding.

http://stackoverflow.com/questions/710158/why-do-my-list-item-bullets-overlap-floating-elements

**Comment by harrybigspring** [comment]
We have decided that the time to fix this is not worth it as this has only ever been an issues on 1 project.
