### ISSUE TITLE
Implement bands

### ISSUE THREAD

**Issue by juliotaylor** [bigspring/M3#6]
A framework to quickly implement full width bands, in a few formats:
- primary
- grey
- standard

Should take into account spacing, padding, header, footer.

```
<section class="band">
  <header><h2>somethin grat</h2></header>
  <div class="band-content">dsfjsdjkfhsdjkh</div>
  <footer><a href="" class="button"></a></footer>
</section>
```

**Comment by harrybigspring** [comment]
Created and added info to Wiki
