### ISSUE TITLE
The builder should be refactored to make better use of pre_get_posts

### ISSUE THREAD

**Issue by jrgmartin** [bigspring/M3#62]
Currently the builder uses WP Query where it can't use the default Wordpress loop object.  This is inefficient because we're using 2 loops (the standard query, plus a new WP_Query) instead of 1.

We should refactor the builder to make use of pre_get_posts instead.

**Comment by dmseaton** [comment]
Using `pre_get_posts` isn't always desirable - the Builder is often used for creating queries in addition to the main query. The question is, should it default to hijacking `pre_get_posts`?

**Comment by jrgmartin** [comment]
Moved to internal issue tracking tool
